machines:
  - nick: example
    name: machine1.example
    box: chef/centos-7.0
    networks:
      - net: private_network
        ip: 192.168.56.100
        mask: 255.255.255.0
      - net: forwarded_port
        guest: 80
        host: 1080
        protocol: tcp
    authorized_keys:
      - type: file
        path: "~/.ssh/id_rsa.pub"
      - type: static
        key: "ssh-rsa fakeSSHpubKEY km@laptop"
    provision:
      - type: shell
        path: "%project.host%/bootstrap.sh"
        args:
          - "%project.guest%"
    shared_folders:
      - host: /Volumes/Repos
        guest: /srv/www
